# Generated by Django 3.1.5 on 2021-05-12 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to='product_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='CookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг повара',
                'verbose_name_plural': 'Рейтинг повара',
            },
        ),
        migrations.CreateModel(
            name='CookMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('cook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to=settings.AUTH_USER_MODEL)),
                ('foods', models.ManyToManyField(blank=True, related_name='menu', to='common.Product')),
            ],
            options={
                'verbose_name': 'Меню повара',
                'verbose_name_plural': 'Меню повара',
            },
        ),
    ]
