# Generated by Django 3.1.5 on 2021-05-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COLLECTION', 'COLLECTION'), ('COOKING', 'COOKING'), ('ASSEMBLY', 'ASSEMBLY'), ('DELIVERY', 'DELIVERY')], default='COLLECTION', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statues', to='order.order')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статус заказа',
            },
        ),
    ]
