# Generated by Django 3.1.5 on 2021-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
