# Generated by Django 3.1.5 on 2021-04-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0002_auto_20210403_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.address'),
        ),
        migrations.CreateModel(
            name='UserPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pin_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пин код пользователя',
                'verbose_name_plural': 'Пин код пользователя',
            },
        ),
    ]
