# Generated by Django 3.1.5 on 2021-04-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210422_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('CASH', 'CASH')], default='ONLINE', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
