# Generated by Django 3.1.5 on 2021-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210422_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars'),
        ),
    ]
