# Generated by Django 3.1.5 on 2021-05-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_coreuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('CASH', 'CASH')], default='CASH', max_length=20),
        ),
    ]
