# Generated by Django 3.1.5 on 2021-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210512_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
